### ISSUE TITLE
[Propuesta] Implementar funcion que permita ir a la url de la incidencia

### ISSUE THREAD

**Issue by monomono2** [bit4bit/jirafa#2]
Aveces es necesario abrir la incidencia para realizar comentarios, avanzar en el flujo de trabajo, etc.
sería bueno implementar la función que lo haga.

Podrías ser algo como: 
jirafa-go-url-issue--at-point

y que ejecutara algo como:

(browse-url (concat "https://" jirafalib-host "/browse" id))

**Comment by bit4bit** [comment]
muy buena, se ha implementado.

puede usar los keybinding de emacs para ejecutar la funcion ver readme
